### PR TITLE
Replace core with cmdliner

### LINKED ISSUE #3: Use stdlib instead of janestreet core?
As far as I can see, core is only used in one file. 
As it is a really big package with lots of dependencies, it really slows down build times. 
Would it be ok to remove it and use the ocaml stdlib instead or is this not possible?

If you would consider it, I could also try to submit a PR. 

Thank you! 😊

### PR DESCRIPTION
**Pull request by eWert-Online**
Fixes #3 

I already replaced most of the functionality with `cmdliner`.
The only thing missing right now is reading from stdin if no file is provided.

I will see, if I can finish the rest tomorrow, but maybe you already want to take a look if it goes in the right direction.

### CODE REVIEW

**Comment by roddyyaga** [comment]
Looks good so far, happy to merge after reading from stdin is added.

**Comment by eWert-Online** [comment]
I added the ability to read from stdin if no files are provided. 
I couldn't really test if it works, because I couldn't figure out how to get the parser to run once it starts reading from stdin (even without my changes).

The behaviour also did change a bit now: 
- **Before:** If the file(s) were not found, it started reading from stdin
- **Now:** If the file(s) are not found, it exits with a non 0 exit code

This could be changed if you want, but I actually think its better that way. 
What do you think?

**Comment by roddyyaga** [comment]
Thanks, looks good! You can test reading from stdin either with (`echo "SELECT * FROM foo;" | pg_check.exe`) or by typing something and pressing Ctrl-D twice to signal EOF (and I can confirm that the .

I agree that the new behaviour is better.

One last thing: could you change the cmdliner documentation about the exit codes to include that it gives 1 on a failed parse (and remove the bit about exit codes from the man page text)? Also feel free to bump the version to 0.9.6 in dune-project and pg_check.ml (it is currently one version behind in the latter) and add an entry to CHANGES.md, or I'm happy to do that.

**Comment by eWert-Online** [comment]
Done! 
I am not sure about the "Fixed" in the CHANGES.md, so feel free to change that or anything else really 🙂

**Pull request merged**
